# Generated by Django 3.0.8 on 2021-06-09 09:36

import BMusers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('element_type', models.IntegerField()),
                ('is_added', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='ElementAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='ElementModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Powerplant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('PPE', models.CharField(max_length=40)),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_added', models.BooleanField(default=False)),
                ('element_type', models.IntegerField()),
                ('POB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PowerplantPOB', to='BMusers.Element')),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlantConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('element_type', models.IntegerField()),
                ('POB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PowerplantElement', to='BMusers.Element')),
                ('PowerPlantItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PowerPlantItem', to='BMusers.Powerplant')),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantConnecionAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='PowerplantConnecionModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=BMusers.models.user_directory_path)),
                ('User', models.ForeignKey(on_delete=models.SET('1'), to=settings.AUTH_USER_MODEL)),
                ('files_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BMusers.Powerplant')),
            ],
        ),
        migrations.CreateModel(
            name='CsprPowerplant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cspr_id', models.IntegerField()),
                ('POB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CsprPowerplantPOB', to='BMusers.Element')),
            ],
        ),
        migrations.CreateModel(
            name='CsprElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=130)),
                ('cspr_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('element_type', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='CsprElementAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='CsprElementModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('POB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POB', to='BMusers.Element')),
                ('SE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SE', to='BMusers.Element')),
                ('author', models.ForeignKey(on_delete=models.SET('1'), related_name='ConnectionAuthor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=models.SET('1'), related_name='ConnectionModifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
